### PR TITLE
Enabled Metadata file saving without hardcoded path separator #10

### PR DESCRIPTION
**Pull request by nemanja-d**

### CODE REVIEW

**Comment by nemanja-d** [comment]
@dina-heidar  Can you please check this pull request and push it on nuget if it is possible..  I need to integrate this fix in next 2 days... please... If it is not possible, I need to copy code, and this is not good solution... :))

thanks in advance...

**Comment by nemanja-d** [comment]
#10

**Comment by dina-heidar** [comment]
@nemanja-d Thanks! Really appreciate it! I'll review the PR tonight. If there are no conflicts I'll merge and package tonight. I'll let you know when it is available.

**Comment by nemanja-d** [comment]
@dina-heidar great!!!  thanks a lot!!

**Comment by dina-heidar** [comment]
I published it now, it should, it appear shortly.  Please let me know when you download and verify if everything is in working order so I can close this issue. There will be a new release soon which will include the fix as well. I Thank you !

**Pull request closed without merging**
